server:
  port: 8000
spring:
  application:
    name: short-link-gateway
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  cloud:
    nacos:
      server-addr: localhost:8848 #nacos服务地址

    gateway:
      routes:   # 网关路由配置
        - id: short-link-admin    # 路由id，自定义，只要唯一即可
          uri: lb://short-link-admin/api/short-link/admin/**  # 路由的目标地址 lb就是负载均衡，后面跟服务名称 + 要代理的路径
          predicates:         # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/api/short-link/admin/**    # 这个是按照路径匹配，只要以/api/short-link/admin/开头就符合要求
          filters:
            - name: TokenValidate    # 使用 TokenValidate 过滤器，对请求进行令牌验证
              args:
                whitePathList: # 白名单路径列表，配置在这些路径下不进行令牌验证
                  - /api/short-link/admin/v1/user/login  # 用户登录接口，无需令牌验证
                  - /api/short-link/admin/v1/user/has-username  # 检查用户名是否存在接口，无需令牌验证

        - id: short-link-project
          uri: lb://short-link-project/api/short-link/**
          predicates:
            - Path=/api/short-link/**
          filters:
            - name: TokenValidate



