server:
  port: 8001
spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379

  mvc:
    view:
      prefix: /templates/
      suffix: .html
  rabbitmq:
    host: 192.168.88.130 # 虚拟机IP
    port: 5672 # 端口
    virtual-host: /hmall # 虚拟主机
    username: hmall # 用户名
    password: 123321 # 密码

short-link:
  domain:
    default: nurl.ink:8001
  stats:
    locale:
      amap-key: 303b853b8d7b4625f83c86d6895cc3c4
  goto-domain:
    white-list:
      enable: true
      names: '拿个offer,知乎,掘金,博客园,B站'
      details:
        - nageoffer.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com
        - bilibili.com
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml